# Generated by Django 6.1.1 on 2026-09-26 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceattempt',
            name='distance_meters',
            field=models.FloatField(blank=True, help_text='Distance from teacher at verification', null=True),
        ),
        migrations.AddField(
            model_name='attendanceattempt',
            name='face_image',
            field=models.TextField(blank=True, help_text='Base64 face snapshot (optional)', null=True),
        ),
        migrations.AddField(
            model_name='attendanceattempt',
            name='face_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendanceattempt',
            name='location_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendanceattempt',
            name='student_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceattempt',
            name='student_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='distance_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='face_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='allowed_radius_meters',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='face_verification_enabled',
            field=models.BooleanField(default=False, help_text='If True, students must pass face scan'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='teacher_latitude',
            field=models.FloatField(blank=True, help_text='Teacher lat at session start', null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='teacher_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='teacher_longitude',
            field=models.FloatField(blank=True, help_text='Teacher lng at session start', null=True),
        ),
        migrations.CreateModel(
            name='LocationDenial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('denied', 'Permission denied'), ('unavailable', 'Location unavailable'), ('timeout', 'Timeout'), ('disabled', 'Disabled')], default='denied', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_denials', to='attendance.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_denials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
