# Generated by Django 6.1.1 on 2026-09-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendanceattempt_distance_meters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceattempt',
            name='face_verified_by_teacher',
            field=models.BooleanField(default=False, help_text='True if teacher captured face via teacher camera'),
        ),
        migrations.AddField(
            model_name='attendanceattempt',
            name='student_location_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='teacher_location_accuracy',
            field=models.FloatField(blank=True, help_text='Accuracy in meters at last update', null=True),
        ),
        migrations.AlterField(
            model_name='attendanceattempt',
            name='face_image',
            field=models.TextField(blank=True, help_text='Base64 face snapshot (teacher camera or student)', null=True),
        ),
    ]
